"""initial setup

Revision ID: 0701db86a48e
Revises: 
Create Date: 2019-12-18 11:16:45.523169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0701db86a48e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64)),
    sa.Column('topLevelDomain', sa.String(length=16)),
    sa.Column('alpha2Code', sa.String(length=16)),
    sa.Column('alpha3Code', sa.String(length=16)),
    sa.Column('callingCodes', sa.String(length=16)),
    sa.Column('flag', sa.String(length=48)),
    sa.Column('population', sa.Integer()),
    sa.Column('capital', sa.String(length=32)),
    sa.Column('timezones', sa.String(length=32)),
    sa.Column('region', sa.String(length=32)),
    sa.Column('nativeName', sa.String(length=64)),
    sa.Column('numericCode', sa.Integer()),
    sa.Column('subregion', sa.String(length=32)),
    sa.Column('currencies', sa.String(length=32)),
    sa.Column('borders', sa.String(length=48)),
    sa.Column('gini', sa.Integer()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=4), nullable=True),
    sa.Column('zipcode', sa.String(length=6), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('addresses')
    op.drop_table('countries')
    # ### end Alembic commands ###
